theme: minima
title: Guedesou Testing
author: Guedesou
email: sradtsor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sou o Guedes. Aprendendo de madrugada.

# social links
twitter_username: thiaguguedes # DO NOT include the @ character, or else the build will fail!
github_username:  Guedesou # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
